version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build-test-monitor:
      docker:
        # specify the version
        - image: circleci/node:latest

      steps:
        - checkout
        - run: npm install semantic-release @semantic-release/exec --save-dev
        - run:
            name: "Install deps"
            command: |
              npm install
        - run:
            name: "Run Tests"
            command: |
              npm test
        - snyk/scan:
            fail-on-issues: true
            monitor-on-build: true
            token-variable: SNYK_TOKEN
        - run: npx semantic-release

  build-test:
      docker:
        # specify the version
        - image: circleci/node:latest

      steps:
        - checkout
        - run:
            name: "Install deps"
            command: |
              npm install
        - run:
            name: "Run Tests"
            command: |
              npm test
        - snyk/scan:
            fail-on-issues: true
            monitor-on-build: false
            token-variable: SNYK_TOKEN

workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test-monitor:
          context: SNYK
  build-test-monitor-publish:
    jobs:
      - build-test-monitor:
          context: SNYK
          filters:
            branches:
              only:
                  - master
  build-test:
      jobs:
        - build-test:
            context: SNYK
            filters:
              branches:
                ignore:
                  - master

